site_name: AeroGameFramework
site_description: Documentation for the AeroGameFramework
site_author: Stephen Leitnick
site_url: https://sleitnick.github.io/AeroGameFramework/

nav:
  - Home: index.md
  - Install & Setup: install.md
  - Services: services.md
  - Controllers: controllers.md
  - Modules: modules.md
  - Execution Model: execution_model.md
  - Module Docs:
      - Server:
        - Modules:
          - ProfileService: module_docs/server_modules/profile_service.md
      - Client:
        - Controllers:
          - UserInput: module_docs/client_controllers/user_input.md
          - UserInput (modules):
              - Mouse: module_docs/client_controllers/user_inputs/mouse.md
              - Keyboard: module_docs/client_controllers/user_inputs/keyboard.md
              - Gamepad: module_docs/client_controllers/user_inputs/gamepad.md
              - Mobile: module_docs/client_controllers/user_inputs/mobile.md
          - Fade: module_docs/client_controllers/fade.md
          - TaskScheduler: module_docs/client_controllers/task_scheduler.md
        - Modules:
          - CameraShaker: module_docs/client_modules/camera_shaker.md
          - Smooth: module_docs/client_modules/smooth.md
          - Tween: module_docs/client_modules/tween.md
          - PID: module_docs/client_modules/pid.md
      - Shared Modules:
        - Base64: module_docs/shared/base64.md
        - Date: module_docs/shared/date.md
        - ListenerList: module_docs/shared/listener_list.md
        - Maid: module_docs/shared/maid.md
        - NumberUtil: module_docs/shared/number_util.md
        - Promise: module_docs/shared/promise.md
        - Signal: module_docs/shared/signal.md
        - StringUtil: module_docs/shared/string_util.md
        - TableUtil: module_docs/shared/table_util.md
        - Thread: module_docs/shared/thread.md
        - VectorUtil: module_docs/shared/vector_util.md

theme:
  logo: "img/logo_64.png"
  favicon: "img/logo_32.png"
  name: material
  palette:
    primary: blue
    accent: blue
  highlightjs: true
  hljs_languages:
    - lua

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Sleitnick/AeroGameFramework

markdown_extensions:
  - codehilite:
      linenums: true
  - admonition
  - toc:
      permalink: true