name: Lint

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lint
      run: |
        wget -O selene https://github.com/Kampfkarren/selene/releases/latest/download/selene-linux
        chmod +x ./selene
        ./selene ./src